import json

with open('notebooks/01_cv_training.ipynb', encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']

# ── cell-6: 1500 images/class instead of 285 ────────────────────────────
cells[6]['source'] = [
    'df_train_raw["label"] = df_train_raw["damage_class"].map(CLASS_TO_IDX)\n',
    'df_val_raw["label"]   = df_val_raw["damage_class"].map(CLASS_TO_IDX)\n',
    '\n',
    '# Use up to 1500 images per class (5x more than before)\n',
    'MAX_PER_CLASS = 1500\n',
    'df_train_raw = df_train_raw.groupby("damage_class", group_keys=False).apply(\n',
    '    lambda x: x.sample(min(len(x), MAX_PER_CLASS), random_state=SEED)\n',
    ').reset_index(drop=True)\n',
    '\n',
    'if len(df_val_raw) > 10:\n',
    '    df_val, df_test = train_test_split(\n',
    '        df_val_raw, test_size=0.2, random_state=SEED,\n',
    '        stratify=df_val_raw["damage_class"]\n',
    '    )\n',
    '    val_img_dir  = VAL_IMG_DIR\n',
    '    test_img_dir = VAL_IMG_DIR\n',
    'else:\n',
    '    df_train_raw, df_val = train_test_split(df_train_raw, test_size=0.15, random_state=SEED, stratify=df_train_raw["damage_class"])\n',
    '    df_train_raw, df_test = train_test_split(df_train_raw, test_size=0.12, random_state=SEED, stratify=df_train_raw["damage_class"])\n',
    '    df_train_raw = df_train_raw.reset_index(drop=True)\n',
    '    val_img_dir  = TRAIN_IMG_DIR\n',
    '    test_img_dir = TRAIN_IMG_DIR\n',
    '\n',
    'df_val  = df_val.reset_index(drop=True)\n',
    'df_test = df_test.reset_index(drop=True)\n',
    'df_ann  = pd.concat([df_train_raw, df_val], ignore_index=True)\n',
    '\n',
    'print(f"Train: {len(df_train_raw)} | Val: {len(df_val)} | Test: {len(df_test)} | Total: {len(df_ann)}")\n',
    'print(df_train_raw["damage_class"].value_counts())\n',
]
cells[6]['outputs'] = []

# ── cell-10: stronger augmentation ──────────────────────────────────────
cells[10]['source'] = [
    'IMG_SIZE   = 224\n',
    'BATCH_SIZE = 32\n',
    '\n',
    'train_transform = transforms.Compose([\n',
    '    transforms.RandomResizedCrop(IMG_SIZE, scale=(0.7, 1.0)),\n',
    '    transforms.RandomHorizontalFlip(p=0.5),\n',
    '    transforms.RandomVerticalFlip(p=0.1),\n',
    '    transforms.RandomRotation(degrees=20),\n',
    '    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.1),\n',
    '    transforms.RandomGrayscale(p=0.1),\n',
    '    transforms.RandomApply([transforms.GaussianBlur(kernel_size=3)], p=0.2),\n',
    '    transforms.ToTensor(),\n',
    '    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),\n',
    '    transforms.RandomErasing(p=0.15, scale=(0.02, 0.1)),\n',
    '])\n',
    '\n',
    'val_transform = transforms.Compose([\n',
    '    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n',
    '    transforms.ToTensor(),\n',
    '    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n',
    '])\n',
    '\n',
    'class VehiDEDataset(Dataset):\n',
    '    def __init__(self, df, img_dir, transform=None):\n',
    '        self.df = df.reset_index(drop=True)\n',
    '        self.img_dir = img_dir\n',
    '        self.transform = transform\n',
    '\n',
    '    def __len__(self):\n',
    '        return len(self.df)\n',
    '\n',
    '    def __getitem__(self, idx):\n',
    '        row = self.df.iloc[idx]\n',
    '        try:\n',
    '            img = Image.open(Path(self.img_dir) / row["filename"]).convert("RGB")\n',
    '        except Exception:\n',
    '            img = Image.new("RGB", (IMG_SIZE, IMG_SIZE), (0, 0, 0))\n',
    '        if self.transform:\n',
    '            img = self.transform(img)\n',
    '        return img, int(row["label"])\n',
    '\n',
    'train_dataset = VehiDEDataset(df_train_raw, TRAIN_IMG_DIR, train_transform)\n',
    'val_dataset   = VehiDEDataset(df_val,       val_img_dir,   val_transform)\n',
    'test_dataset  = VehiDEDataset(df_test,      test_img_dir,  val_transform)\n',
    '\n',
    'class_counts   = Counter(df_train_raw["label"].tolist())\n',
    'class_weights  = {cls: 1.0 / cnt for cls, cnt in class_counts.items()}\n',
    'sample_weights = [class_weights[lbl] for lbl in df_train_raw["label"].tolist()]\n',
    'sampler        = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)\n',
    '\n',
    'num_workers  = 2 if torch.cuda.is_available() else 0\n',
    'train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=sampler,\n',
    '                          num_workers=num_workers, pin_memory=torch.cuda.is_available())\n',
    'val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False,\n',
    '                          num_workers=num_workers, pin_memory=torch.cuda.is_available())\n',
    'test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False,\n',
    '                          num_workers=num_workers, pin_memory=torch.cuda.is_available())\n',
    '\n',
    'print(f"Train: {len(train_dataset)} | Val: {len(val_dataset)} | Test: {len(test_dataset)}")\n',
]
cells[10]['outputs'] = []

# ── cell-12: improved train_model with early stopping + label smoothing + AMP ─
cells[12]['source'] = [
    'def build_resnet18(num_classes):\n',
    '    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)\n',
    '    model.fc = nn.Linear(model.fc.in_features, num_classes)\n',
    '    return model\n',
    '\n',
    'def train_epoch(model, loader, optimizer, criterion, scaler=None):\n',
    '    model.train()\n',
    '    total_loss, correct, total = 0, 0, 0\n',
    '    for images, labels in tqdm(loader, leave=False):\n',
    '        images, labels = images.to(DEVICE), labels.to(DEVICE)\n',
    '        optimizer.zero_grad()\n',
    '        if scaler is not None:\n',
    '            with torch.amp.autocast("cuda"):\n',
    '                outputs = model(images)\n',
    '                loss = criterion(outputs, labels)\n',
    '            scaler.scale(loss).backward()\n',
    '            scaler.unscale_(optimizer)\n',
    '            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n',
    '            scaler.step(optimizer)\n',
    '            scaler.update()\n',
    '        else:\n',
    '            outputs = model(images)\n',
    '            loss = criterion(outputs, labels)\n',
    '            loss.backward()\n',
    '            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n',
    '            optimizer.step()\n',
    '        total_loss += loss.item()\n',
    '        correct += (outputs.argmax(1) == labels).sum().item()\n',
    '        total += labels.size(0)\n',
    '    return total_loss / len(loader), correct / total\n',
    '\n',
    'def eval_epoch(model, loader, criterion):\n',
    '    model.eval()\n',
    '    total_loss, correct, total = 0, 0, 0\n',
    '    with torch.no_grad():\n',
    '        for images, labels in loader:\n',
    '            images, labels = images.to(DEVICE), labels.to(DEVICE)\n',
    '            outputs = model(images)\n',
    '            loss = criterion(outputs, labels)\n',
    '            total_loss += loss.item()\n',
    '            correct += (outputs.argmax(1) == labels).sum().item()\n',
    '            total += labels.size(0)\n',
    '    return total_loss / len(loader), correct / total\n',
    '\n',
    'def train_model(model, train_loader, val_loader, epochs=20, lr=1e-3,\n',
    '                model_name="model", freeze_epochs=3, patience=5):\n',
    '    """\n',
    '    freeze_epochs: train only the classifier head for this many epochs,\n',
    '                   then unfreeze the full backbone for fine-tuning.\n',
    '    patience:      early stopping patience on val_acc.\n',
    '    """\n',
    '    model     = model.to(DEVICE)\n',
    '    use_amp   = DEVICE.type == "cuda"\n',
    '    scaler    = torch.amp.GradScaler("cuda") if use_amp else None\n',
    '    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)\n',
    '\n',
    '    # Phase 1: freeze backbone, train head only\n',
    '    for name, param in model.named_parameters():\n',
    '        param.requires_grad = any(k in name for k in ("classifier", "fc", "head"))\n',
    '\n',
    '    optimizer = optim.AdamW(\n',
    '        filter(lambda p: p.requires_grad, model.parameters()),\n',
    '        lr=lr, weight_decay=1e-4)\n',
    '    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)\n',
    '\n',
    '    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}\n',
    '    best_val_acc = 0\n',
    '    no_improve   = 0\n',
    '\n',
    '    for epoch in range(epochs):\n',
    '        # Phase 2: unfreeze all after freeze_epochs\n',
    '        if epoch == freeze_epochs:\n',
    '            print(f"  >> Unfreezing all layers at epoch {epoch+1}")\n',
    '            for param in model.parameters():\n',
    '                param.requires_grad = True\n',
    '            optimizer = optim.AdamW(model.parameters(), lr=lr / 5, weight_decay=1e-4)\n',
    '            scheduler = optim.lr_scheduler.CosineAnnealingLR(\n',
    '                optimizer, T_max=epochs - freeze_epochs)\n',
    '\n',
    '        train_loss, train_acc = train_epoch(model, train_loader, optimizer, criterion, scaler)\n',
    '        val_loss, val_acc     = eval_epoch(model, val_loader, criterion)\n',
    '        scheduler.step()\n',
    '\n',
    '        history["train_loss"].append(train_loss)\n',
    '        history["val_loss"].append(val_loss)\n',
    '        history["train_acc"].append(train_acc)\n',
    '        history["val_acc"].append(val_acc)\n',
    '\n',
    '        print(f"Epoch {epoch+1:02d}/{epochs} | "\n',
    '              f"Train Loss: {train_loss:.4f} Acc: {train_acc:.4f} | "\n',
    '              f"Val Loss: {val_loss:.4f} Acc: {val_acc:.4f}")\n',
    '\n',
    '        if val_acc > best_val_acc:\n',
    '            best_val_acc = val_acc\n',
    '            no_improve   = 0\n',
    '            torch.save(model.state_dict(), MODELS_DIR / f"{model_name}_best.pth")\n',
    '        else:\n',
    '            no_improve += 1\n',
    '            if no_improve >= patience:\n',
    '                print(f"  >> Early stopping at epoch {epoch+1}")\n',
    '                break\n',
    '\n',
    '    print(f"\\nBest Val Accuracy: {best_val_acc:.4f}")\n',
    '    return history\n',
]
cells[12]['outputs'] = []

# ── cell-13: ResNet-18 — 10 epochs ──────────────────────────────────────
cells[13]['source'] = [
    'NUM_CLASSES = len(DAMAGE_CLASSES)\n',
    'resnet18 = build_resnet18(NUM_CLASSES)\n',
    'print(f"ResNet-18 parameters: {sum(p.numel() for p in resnet18.parameters()):,}")\n',
    '\n',
    'history_resnet = train_model(resnet18, train_loader, val_loader,\n',
    '                             epochs=10, model_name="resnet18",\n',
    '                             freeze_epochs=2, patience=5)\n',
]
cells[13]['outputs'] = []

# ── cell-15: EfficientNet-B2, 20 epochs ─────────────────────────────────
cells[15]['source'] = [
    'def build_efficientnet_b2(num_classes):\n',
    '    # B2: stronger than B0 (9.1M params, ~82% ImageNet top-1 vs 77%)\n',
    '    model = timm.create_model("efficientnet_b2", pretrained=True, num_classes=num_classes)\n',
    '    return model\n',
    '\n',
    'efficientnet = build_efficientnet_b2(NUM_CLASSES)\n',
    'print(f"EfficientNet-B2 parameters: {sum(p.numel() for p in efficientnet.parameters()):,}")\n',
    '\n',
    '# Saved as efficientnet_b0_best.pth to stay compatible with the deployed app\n',
    'history_effnet = train_model(efficientnet, train_loader, val_loader,\n',
    '                             epochs=20, model_name="efficientnet_b0",\n',
    '                             freeze_epochs=3, patience=6)\n',
]
cells[15]['outputs'] = []

# ── cell-24: updated summary ─────────────────────────────────────────────
cells[24]['source'] = [
    '## Summary\n',
    '\n',
    '| Model | Architecture | Epochs | Data/class | Test Accuracy | Params |\n',
    '|---|---|---|---|---|---|\n',
    '| Baseline | ResNet-18 | 10 (early stop) | 1500 | — | 11.7M |\n',
    '| Primary  | EfficientNet-B2 | 20 (early stop) | 1500 | — | 9.1M |\n',
    '\n',
    'Improvements over v1:\n',
    '- **5x more training data** per class (285 → 1500)\n',
    '- **4x more epochs** with early stopping (patience=6)\n',
    '- **Stronger augmentation**: RandomResizedCrop, GaussianBlur, RandomErasing\n',
    '- **Label smoothing** (0.1) to reduce overconfidence on noisy labels\n',
    '- **Gradual unfreezing**: head-only first 3 epochs, then full fine-tune at lr/5\n',
    '- **Mixed precision (AMP)** on GPU for 2-3x faster Colab training\n',
    '- **EfficientNet-B2** instead of B0 (larger capacity, better pretrained weights)\n',
]

with open('notebooks/01_cv_training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('Notebook updated successfully.')
